
# Import from the Hub -----------------------------------------------------
```{r eval = FALSE}
library(tidyverse)
library(aws.s3)
Sys.setenv("AWS_DEFAULT_REGION" = "us-east-2")
s3bucket <- get_bucket("forecast-eval")
n_keeper_weeks <- 6L
n_keeper_locs <- 50L
# case_scores <- s3readRDS("score_cards_state_cases.rds", s3bucket) 
case_preds <- s3readRDS("predictions_cards.rds", s3bucket) %>%
  filter(signal == "confirmed_incidence_num",
         forecast_date < "2021-01-01",
         !(geo_value %in% c("as", "gu", "pr", "vi", "mp", "us"))) %>%
  select(-data_source, -signal, -incidence_period)
actuals <- covidcast::covidcast_signal("jhu-csse", "confirmed_7dav_incidence_num",
                                       geo_type = "state", as_of = "2021-05-18",
                                       end_day = "2021-03-01") %>%
  select(geo_value, time_value, value) %>%
  mutate(value = value * 7) %>%
  rename(target_end_date = time_value, actual = value)
case_scores <- evalcast::evaluate_predictions(
  case_preds, actuals, 
  err_measures = list(wis = evalcast::weighted_interval_score),
  grp_vars = c("ahead", "forecaster", "forecast_date", "geo_value")
)
rm(case_preds)
case_scores <- case_scores %>% 
  mutate(
    ahead = ahead * 7 - 2, # forecast on a Tuesday
    forecast_date = target_end_date - ahead) %>% 
  # fix weirdnesses about submission dates
  filter(forecast_date < "2021-01-01") %>%
  select(ahead, geo_value, forecaster, target_end_date, wis, forecast_date)

strawman <- case_scores %>% filter(forecaster == "COVIDhub-baseline")
case_scores <- left_join(
  case_scores, 
  strawman %>% 
    select(forecast_date, target_end_date, geo_value, wis) %>% 
    rename(strawman_wis = wis)
  )
case_scores <- case_scores %>% 
  filter(forecaster != "COVIDhub-baseline")
aheads <- case_scores %>% distinct(ahead) %>% pull()
n_submitted <- case_scores %>% 
  filter(ahead == aheads[2]) %>% 
  group_by(forecaster) %>% 
  summarise(nfcasts = n())
keepers <- n_submitted %>% 
  filter(nfcasts / n_keeper_locs > n_keeper_weeks - .0001) %>% 
  # submitted at least z weeks for x locations
  pull(forecaster)

case_scores <- case_scores %>% filter(forecaster %in% keepers)
```

# Load our models ---------------------------------------------------------
```{r}
library(tidyverse)
ours <- readRDS(here::here("data", "results_honest_states.RDS")) %>%
  filter(forecaster != "AR3GSSAA3_Subset")
pop <- covidcast::state_census %>% select(ABBR, POPESTIMATE2019) %>%
  mutate(geo_value = tolower(ABBR)) %>% select(-ABBR)
# scale from prop to num
ours2 <- left_join(ours, pop, by = "geo_value") %>%
  mutate(wis = wis, #* POPESTIMATE2019, #/ 1e5 * 7,
         forecaster = recode(forecaster,
                             AR3 = "AR",
                             AR3CHCLI3 = "CHNG-CLI",
                             AR3CHCOV3 = "CHNG-COVID",
                             AR3DVCLI3 = "DV-CLI",
                             AR3FBCLI3 = "CTIS-CLIIC",
                             AR3GSSAA3_Zero = "Google-AA")) %>%
  select(-ae, -POPESTIMATE2019) 

# Join sanity check
nrow(ours) == nrow(ours2)
ours = ours2
```

```{r}
our_models <- ours %>% filter(forecaster != "Baseline")
baseline <- ours %>% filter(forecaster == "Baseline") %>%
  select(-forecaster) %>% rename(strawman_wis = wis)
our_models <- left_join(our_models, baseline)

# Sanity check: left join
nrow(our_models) == nrow(ours) - sum(ours$forecaster == "Baseline")

# Sanity check: missingness
our_models %>%
  group_by(forecaster) %>%
  summarize(sum(is.na(wis)))

our_models %>% summarize(sum(is.na(strawman_wis)))

Mean <- function(x) mean(x, na.rm = TRUE)
GeoMean <- function(x) exp(mean(log(x), na.rm = TRUE))

all_models = our_models
all_time_performance <- all_models %>%
  #filter(forecast_date %in% common_fd) %>%
  group_by(forecaster, ahead) %>% #, source) %>%
  summarise(rel_wis = Mean(wis) / Mean(strawman_wis),
            geo_wis = GeoMean((wis) / (strawman_wis))) %>%
  pivot_longer(contains("wis"))

facet_labs <- c(geo_wis = "Geometric mean of WIS", rel_wis = "Mean of WIS")
fcast_colors <- c(RColorBrewer::brewer.pal(5, "Set1"), "#000000")
names(fcast_colors) <- c("CHNG-CLI", "CHNG-COVID", "CTIS-CLIIC", "DV-CLI",
                         "Google-AA", "AR")


ggplot(all_time_performance %>% filter(ahead <= 21), 
       aes(ahead, value, color = forecaster)) +
  geom_line(aes(ahead, value, color = forecaster)) + 
  geom_point(aes(ahead, value, color = forecaster)) +
  scale_color_manual(values = fcast_colors, guide = guide_legend(nrow = 1)) +
  theme_bw() +
  ylab("Score relative to baseline") +
  geom_hline(yintercept = 1, size = 1.5) +
  xlab("Days ahead") +
  facet_wrap(~ name, labeller = labeller(name = facet_labs), scales = "free_y") +
  theme(legend.position = "bottom", legend.title = element_blank())
```

```{r}
p1 <- ours %>% 
  group_by(forecaster, ahead) %>%
  summarize(mean_wis = Mean(wis)) %>%
  ggplot(aes(x = ahead, y = mean_wis, color = forecaster)) + 
  geom_line() + geom_point() +   
  xlab("Days ahead") + ylab("Mean WIS") + 
  scale_color_manual(values = fcast_colors, guide = guide_legend(nrow = 1)) +
  theme_bw() +
  theme(legend.position = "bottom", legend.title = element_blank())
  
p2 <- ours %>% 
  group_by(forecaster, ahead) %>%
  summarize(geomean_wis = GeoMean(wis)) %>%
  ggplot(aes(x = ahead, y = geomean_wis, color = forecaster)) + 
  geom_line() + geom_point() +   
  xlab("Days ahead") + ylab("Geo mean WIS") + 
  scale_color_manual(values = fcast_colors, guide = guide_legend(nrow = 1)) +
  theme_bw() +
  theme(legend.position = "bottom", legend.title = element_blank())

gridExtra::grid.arrange(p2, p1, nrow = 1)
```

# Try with other code
```{r}  
library(tidyverse)
library(lubridate)
source(here::here("code", "figures", "results_processing_and_plotting.R"))
source(here::here("code", "figures", "eval_funs.R"))
ours3 <- readRDS(here::here("data", "results_honest_states.RDS")) %>%
  process_res_cases(actuals) %>%
  filter(forecaster != "gs_subset") %>%
  filter(forecaster != "gs_inherit") %>%
  mutate(forecaster = recode(forecaster, gs = "Google-AA"))

unique(ours3$forecaster)[!(unique(ours3$forecaster) %in% names(fcast_colors))]

p1 <- plotter(ours3 %>% filter(ahead <= 21), 
        "wis", Mean, scaler = "strawman_wis", 
        order_of_operations = c("aggr","scale")) +
  ylab("Mean WIS (relative to baseline)")

p2 <- plotter(ours3 %>% filter(ahead <= 21), 
        "wis", GeoMean, scaler = "strawman_wis", 
        order_of_operations = c("aggr","scale")) +
  ylab("Geometric mean WIS (relative to baseline)")

gridExtra::grid.arrange(p2, p1, nrow = 1)
```

# Load our HRR results ---------------------------------------------------------
```{r eval = FALSE}
source(here::here("code", "figures", "results_processing_and_plotting.R"))
source(here::here("code", "figures", "eval_funs.R"))

actuals <- readRDS(here::here("data", "confirmed_7dav_incidence_prop.RDS"))
fcasts_honest <- readRDS(here::here("data", "results_honest.RDS")) 
  process_res_cases(actuals) %>%
  filter(forecaster != "gs_subset") %>%
  filter(forecaster != "gs_inherit") %>%
  mutate(forecaster = recode(forecaster, gs = "Google-AA"))

p1 <- plotter(ours3 %>% filter(ahead <= 21), 
        "wis", Mean, scaler = "strawman_wis", 
        order_of_operations = c("aggr","scale")) +
  ylab("Mean WIS (relative to baseline)")

p2 <- plotter(ours3 %>% filter(ahead <= 21), 
        "wis", GeoMean, scaler = "strawman_wis", 
        order_of_operations = c("aggr","scale")) +
  ylab("Geometric mean WIS (relative to baseline)")

gridExtra::grid.arrange(p2, p1, nrow = 1)
```
