---
title: Correlation analysis to inferred infection rates (deconvolved case rates)
---

```{r, include = FALSE}
knitr::opts_chunk$set(cache = TRUE, autodep = TRUE, cache.comments = TRUE, 
                      message = FALSE, warning = FALSE)
```

```{r, messages = FALSE}
library(covidcast)
library(dplyr)
library(ggplot2)

start_day <- "2020-04-15"
end_day <- "2021-04-15"
geo_type <- "state"
cli <- covidcast_signal(data_source = "fb-survey",
                        signal = "smoothed_wcli",
                        start_day, end_day, geo_type)
cmt <- covidcast_signal(data_source = "fb-survey",
                        signal = "smoothed_whh_cmnty_cli",
                        start_day, end_day, geo_type)
cases <- covidcast_signal(data_source = "usa-facts",
                          signal = "confirmed_7dav_incidence_prop",
                        start_day, end_day, geo_type)

deconv <- read.csv("deconv_data.csv")
deconv <- as.covidcast_signal(deconv, signal = deconv$signal[1])
deconv$time_value <- as.Date(deconv$time_value)
```

## Geo-wise correlations (sliced by time)

```{r}
# Compute correlation per time, over all counties
by = "time_value"
cor_geowise <- rbind(
  data.frame(covidcast_cor(cli, deconv, by = by), signal = "cli-deconv"),
  data.frame(covidcast_cor(cmt, deconv, by = by), signal = "cmt-deconv"),
  data.frame(covidcast_cor(cli, cases, by = by), signal = "cli-cases"),
  data.frame(covidcast_cor(cmt, cases, by = by), signal = "cmt-cases"))

ggplot(cor_geowise, aes(x = time_value, y = value)) +
  geom_line(aes(color = signal)) +
  scale_x_date(date_breaks = "3 months", date_labels = "%b %Y",
               date_minor_breaks = "1 month") + 
  labs(x = "Date", y = "Correlation") + theme_bw() +
  theme(legend.position = "bottom", legend.title = element_blank())
#ggsave("../fig/deconv_geowise_corr.pdf", width = 5, height = 3.5)
```

## Time-wise correlations (sliced by location)

```{r}
# Compute correlation per location, over all time
by <- "geo_value"
cor_timewise <- rbind(
  data.frame(covidcast_cor(cli, deconv, by = by), signal = "cli-deconv"),
  data.frame(covidcast_cor(cmt, deconv, by = by), signal = "cmt-deconv"),
  data.frame(covidcast_cor(cli, cases, by = by), signal = "cli-cases"),
  data.frame(covidcast_cor(cmt, cases, by = by), signal = "cmt-cases"))
                            
ggplot(cor_timewise, aes(value)) +
  geom_density(aes(color = signal, fill = signal), alpha = 0.4) +
  labs(x = "Correlation", y = "Density") + theme_bw() +
  theme(legend.position = "bottom", legend.title = element_blank())
#ggsave("../fig/deconv_timewise_corr.pdf", width = 5, height = 3.5)
```

## More systematic lag analysis

```{r}
# Loop over values for dt, and compute correlations per state
dt_vec <- (-20):20
by <- "geo_value"
cor_timewise_list <- vector("list", length(dt_vec))
for (i in 1:length(dt_vec)) {
  cor_timewise_list[[i]] <- rbind(
    data.frame(covidcast_cor(cli, deconv, dt_x = dt_vec[i], by = by), 
               dt = dt_vec[i], signal = "cli-deconv"),
    data.frame(covidcast_cor(cmt, deconv, dt_x = dt_vec[i], by = by), 
               dt = dt_vec[i], signal = "cmt-deconv"),
    data.frame(covidcast_cor(cli, cases, dt_x = dt_vec[i], by = by), 
               dt = dt_vec[i], signal = "cli-cases"),
    data.frame(covidcast_cor(cmt, cases, dt_x = dt_vec[i], by = by), 
               dt = dt_vec[i], signal = "cmt-cases"),
    data.frame(covidcast_cor(cli, cmt, dt_x = dt_vec[i], by = by), 
               dt = dt_vec[i], signal = "cli-cmt"))
}

# Stack into one big data frame, and then plot the mean correlation by dt
cor_timewise_dt <- do.call(rbind, cor_timewise_list)
cor_timewise_dt %>%
  group_by(dt, signal) %>%
  summarize(value = mean(value, na.rm = TRUE), .groups = "drop_last") %>%
  ggplot(aes(x = dt, y = value)) + 
  geom_line(aes(color = signal)) + geom_point(aes(color = signal)) +
  labs(x = "dt", y = "Correlation") + theme_bw() +
  theme(legend.position = "bottom", legend.title = element_blank())

cor_timewise_dt %>%
  group_by(dt, signal) %>%
  summarize(value = median(value, na.rm = TRUE), .groups = "drop_last") %>%
  ggplot(aes(x = dt, y = value)) + 
  geom_line(aes(color = signal)) + geom_point(aes(color = signal)) +
  labs(x = "dt", y = "Correlation") + theme_bw() +
  theme(legend.position = "bottom", legend.title = element_blank())
```