---
bibliography: [../../common/covidcast.bib]
output: 
  pdf_document:
    keep_tex: true
    template: pnas-suppl-template.tex
params:
  fd_casefloor: 30
  flag_jumps: 15
---




\input{supplement-text.tex}



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.width = 6.5, fig.height = 4.5,
                      fig.align = "center",
                      fig.path = "fig/",
                      cache = TRUE, 
                      out.width = "\\textwidth",
                      autodep = TRUE,
                      message = FALSE, 
                      warning = FALSE)
```

```{r source-funs, cache=FALSE}
library(scales)
library(cowplot)
library(covidcast)
library(tidyverse)
library(lubridate)
library(evalcast)
library(here)

source(here("code", "figures", "results_processing_and_plotting.R"))
source(here("code", "figures", "eval_funs.R"))
source(here("code", "figures", "hotspot_funs.R"))

```

```{r data-loading}
actuals <- readRDS(here("data", "confirmed_7dav_incidence_prop.RDS"))
fcasts_honest <- readRDS(here("data", "revised_chng", "results_honest.RDS")) %>%
  process_res_cases(actuals) %>%
  filter(forecaster != "gs_inherit") 
fcasts_finalized <- readRDS(here("data", "results_dishonest.RDS")) %>%
  process_res_cases(actuals) %>%
  filter(forecaster != "gs_inherit")
hotspots_honest <- readRDS(here("data", "revised_chng", "hotspots_honest.RDS")) %>%
  process_res_hotspots() %>%
  filter(forecaster != "gs_inherit")
hotspots_finalized <- readRDS(here("data", "hotspots_dishonest.RDS")) %>%
  process_res_hotspots() %>%
  filter(forecaster != "gs_inherit")
cases7dav <- readRDS(here("data", "confirmed_7dav_incidence_num.RDS")) %>%
  rename(case_num = value)
if (params$fd_casefloor >= 0) {
  fcasts_honest <- filter_case_floor(fcasts_honest, cases7dav, params)
  fcasts_finalized <- filter_case_floor(fcasts_finalized, cases7dav, params)
}
if (params$flag_jumps > 0) {
  fcasts_honest <- filter_jumps(fcasts_honest, actuals, params)
  fcasts_finalized <- filter_jumps(fcasts_finalized, actuals, params)
  hotspots_honest <- filter_jumps(hotspots_honest, actuals, params)
  hotspots_finalized <- filter_jumps(hotspots_finalized, actuals, params)
}
```

```{r gs-processing}
# only honest
fcasts_gs <- intersect_averagers(
  fcasts_honest, "forecaster", 
  c("geo_value", "ahead", "forecast_date", "target_end_date")) %>%
  filter(forecaster != "gs_subset") %>%
  mutate(forecaster = recode(forecaster, gs = "Google-AA"))
fcasts_honest <- filter(fcasts_honest, forecaster != "gs_subset") %>%
  mutate(forecaster = recode(forecaster, gs = "Google-AA"))
fcasts_finalized <- filter(fcasts_finalized, forecaster != "gs_subset")%>%
  mutate(forecaster = recode(forecaster, gs = "Google-AA"))
hotspots_gs <- intersect_averagers(
  hotspots_honest %>% filter(!is.na(value), !is.na(actual)), 
  "forecaster", 
  c("geo_value", "ahead", "forecast_date", "target_end_date")) %>%
  filter(forecaster != "gs_subset") %>%
  mutate(forecaster = recode(forecaster, gs = "Google-AA"))
hotspots_honest <- intersect_averagers( # Deal with DV NaN's
  hotspots_honest %>% 
    filter(! is.na(value), !is.na(actual), forecaster != "gs_subset"), 
  "forecaster", 
  c("geo_value", "ahead", "forecast_date", "target_end_date")) %>%
  mutate(forecaster = recode(forecaster, gs = "Google-AA"))
hotspots_finalized <- intersect_averagers( 
  hotspots_finalized %>% 
    filter(! is.na(value), !is.na(actual), forecaster != "gs_subset"), 
  "forecaster", 
  c("geo_value", "ahead", "forecast_date", "target_end_date")) %>%
  mutate(forecaster = recode(forecaster, gs = "Google-AA"))
```

```{r hrr-names}
hrr_names <- read_csv(here("data", "Hospital_Referral_Regions.csv"), 
                      col_types = "_ccc__") %>%
  mutate(state = substr(hrrcity, 1, 2),
         hrrname = paste(HRR_lbl, state)) %>%
  select(hrrnum, hrrname)
hrr_tab <- pull(hrr_names, hrrname)
names(hrr_tab) <- pull(hrr_names, hrrnum)
```



<!-- All figures and tables below this line -->



<!-- Finalized v. vintage -->

```{r fcast, include=FALSE}
# Figure 3 in the paper
fig3 <- plotter(fcasts_honest, 
        "wis", Mean, scaler = "strawman_wis", 
        order_of_operations = c("aggr","scale")) +
  ylab("Mean WIS (relative to baseline)")
fig3
```

```{r hot, include=FALSE}
# Figure 4 in the manuscript
fig4 <- plotter_hotspots(hotspots_honest) + 
  geom_hline(yintercept = 0.5)
fig4
```

```{r fcast-hot-combo, include=FALSE, fig.width=9, fig.height=4.5}
leg <- get_legend(fig3)
comb1 <- plot_grid(fig3 + theme(legend.position = "none"),
                   fig4 + theme(legend.position = "none"), 
                   nrow = 1)
plot_grid(comb1, leg, ncol = 1, rel_heights = c(1,.1))
```




```{r fcast-finalized, fig.cap="Forecasting performance using finalized data. Compare to Figure 3 in the manuscript."}
plotter(fcasts_finalized, 
        "wis", Mean, scaler = "strawman_wis", 
        order_of_operations = c("aggr","scale")) +
  ylab("Mean WIS (relative to baseline)")
```


\clearpage


```{r hot-finalized, fig.cap="Hotspot prediction performance using finalized data. Compare to Figure 4 in the manuscript."}
plotter_hotspots(hotspots_finalized) +
  geom_hline(yintercept = 0.5)
```

\clearpage


```{r fcast-honest-v-finalized, fig.cap="Relative forecast WIS with vintage compared to finalized data. Using finalized data leads to overly optimistic performance."}
plotter(
  left_join(
    fcasts_honest %>% select(forecaster:wis),
    fcasts_finalized %>% select(forecaster:wis) %>%
      rename(finalized_wis = wis)
    ), 
  "wis", Mean, scaler = "finalized_wis", 
  order_of_operations = c("aggr","scale")) +
  geom_hline(yintercept = 1) +
  ylab("Mean WIS (vintage / finalized)")

```

\clearpage

```{r hot-honest-v-finalized, fig.cap="Relative AUC with vintage compared to finalized data. Using finalized data leads to overly optimistic hotspot performance."}
left_join(
  hotspots_honest %>%
    group_by(forecaster, ahead) %>%
    summarise(auc_honest = auc(value, actual)),
  hotspots_finalized %>%
    group_by(forecaster, ahead) %>%
    summarise(auc_finalized = auc(value, actual))) %>%
  ggplot(aes(ahead, auc_honest / auc_finalized, color = forecaster)) + 
  geom_line() + 
  geom_point() +
  theme_bw() + 
  scale_color_manual(values = fcast_colors, guide = guide_legend(nrow=1)) +
  theme(legend.position = "bottom", legend.title = element_blank()) +
  geom_hline(yintercept = 1) +
  ylab("AUC (vintage / finalized)")
```




\clearpage



<!-- Geometric mean justifications -->


```{r wis-densities, fig.cap="Weighted interval score appears to more closely resemble a log-Gaussian distribution."}
ggplot(fcasts_honest, 
       aes(wis, fill = forecaster)) +
  geom_density() +
  scale_x_log10() +
  theme_bw() +
  xlab("WIS") +
  scale_fill_manual(values = fcast_colors) +
  facet_wrap(~forecaster) +
  theme(legend.position = "none")
```

\clearpage

```{r fcast-adjusted, fig.cap="Relative forecast performance using vintage data and summarizing with the more robust geometric mean."}
plotter(fcasts_honest, 
        "wis", GeoMean, scaler = "strawman_wis", 
        order_of_operations = c("scale","aggr")) +
  ylab("Geometric mean of WIS (relative to baseline)")
```


\clearpage

<!-- Statistical significance -->

```{r sign-test, fig.cap="P-values for a sign test that the WIS of the AR forecaster is smaller than that of the indicator-assisted model. Each P-value corresponds a particular forecast date."}
fcast_colors2 <- fcast_colors[names(fcast_colors) != "AR"]

st <- fcasts_honest %>%
  mutate(wis = wis / strawman_wis) %>%
  select(forecaster, geo_value, ahead, forecast_date, wis) %>%
  pivot_wider(names_from = forecaster, values_from = wis) %>%
  mutate(across(AR:`Google-AA`, ~ AR - .x)) %>%
  select(-AR) %>%
  pivot_longer(`CHNG-CLI`:`Google-AA`, names_to = "forecaster", values_to = "dif") %>%
  group_by(forecaster, forecast_date, geo_value) %>%
  summarise(dif = sum(dif)) %>%
  group_by(forecaster, forecast_date) %>%
  summarise(p = binom.test(
    x = sum(dif > 0),
    n = n(),
    alternative = "greater")$p.val)

ggplot(st, aes(p)) +
  geom_histogram(
    aes(y = after_stat(density), color = forecaster, fill = forecaster), 
    alpha = 0.4,
    bins = 40) +
  scale_color_manual(values = fcast_colors2, guide = guide_legend(nrow = 1)) +
  scale_fill_manual(values = fcast_colors2, guide = guide_legend(nrow = 1)) +
  facet_wrap(~forecaster) +
  ylab("Frequency") +
  xlab("P-value") +
  scale_y_continuous(
    labels = scales::percent_format(scale = 1, accuracy = 1)) +
  theme_bw() +
  theme(legend.position = "bottom")

```


```{r dm-test}
errs <- fcasts_honest %>% 
  group_by(forecaster, forecast_date) %>%
  summarise(
    `Mean Relative WIS` = mean(wis) / mean(strawman_wis),
    # mwis = mean(wis), 
    `Geometric Mean Relative WIS` = GeoMean(wis / strawman_wis) #,
    # gmwis = GeoMean(wis)
    ) %>%
  ungroup()
ar <- errs %>% 
  filter(forecaster == "AR") %>% 
  select(-forecaster) %>%
  pivot_longer(-forecast_date, names_to = "metric", values_to = "AR")
notar <- errs %>%
  filter(forecaster != "AR") %>% 
  pivot_longer(-c("forecaster", "forecast_date"), names_to = "metric", values_to = "err")

all_errs <- left_join(notar, ar)
dms <- all_errs %>% 
  group_by(forecaster, metric) %>% 
  summarise(dm = forecast::dm.test(AR, err, "greater", h = 7 , power = 1)$p.value)



kableExtra::kable(
  bind_rows(dms) %>% 
    pivot_wider(names_from = forecaster, values_from = dm), 
  digits = 3, booktabs = TRUE, caption = "$P$-values for a one-sided Diebold-Mariano test for improvement in forecast error. The test is for the null hypothesis of equal performance against the alternative that the indicator assisted model is better.")
```


<!-- Bootstrap stuff -->

```{r bootstrap-loading}
fcasts_booted <- readRDS(
  here("data", "results_honest_bootstrapped.RDS")) %>%
  process_res_cases(actuals) %>%
  filter(forecaster != "gs_inherit")
if (params$fd_casefloor >= 0) {
  fcasts_booted <- filter_case_floor(fcasts_booted, cases7dav, params)
}
hotspots_booted <- readRDS(here("data", "revised_chng", "hotspots_honest_bootstrapped.RDS")) %>%
  process_res_hotspots() %>%
  filter(forecaster != "gs_inherit")
if (params$flag_jumps > 0) {
  hotspots_booted <- filter_jumps(hotspots_booted, actuals, params)
  fcasts_booted <- filter_jumps(fcasts_booted, actuals, params)
}
fcasts_booted <- filter(fcasts_booted, forecaster != "gs_subset") %>%
  mutate(forecaster = recode(forecaster, gs = "Google-AA"))
hotspots_booted <- intersect_averagers( # Deal with DV NaN's
  hotspots_booted %>% 
    filter(! is.na(value), !is.na(actual), forecaster != "gs_subset"), 
  "forecaster", 
  c("geo_value", "ahead", "forecast_date", "target_end_date")) %>%
  mutate(forecaster = recode(forecaster, gs = "Google-AA"))
```

```{r fcast-booted, fig.cap = "Forecast performance when indicators are replaced with samples from their empirical distribution. Performance is largely similar to the AR model."}
plotter(fcasts_booted, 
        "wis", Mean, scaler = "strawman_wis", 
        order_of_operations = c("aggr","scale")) +
  ylab("Mean WIS (relative to baseline)")
```

\clearpage

```{r fcast-booted-adjusted, fig.cap = "Forecast performance as measured with the geometric mean when indicators are replaced with samples from their empirical distribution. Performance is largely similar to the AR model."}
plotter(fcasts_booted, 
        "wis", GeoMean, scaler = "strawman_wis", 
        order_of_operations = c("scale","aggr")) +
  ylab("Geometric mean of WIS (relative to baseline)")
```

\clearpage

```{r hot-booted, fig.cap = "Hotspot prediction performance when indicators are replaced with samples from their empirical distribution. Performance is largely similar to the AR model."}
plotter_hotspots(hotspots_booted) + 
  geom_hline(yintercept = 0.5)
```



\clearpage





<!-- Upswings vs. downswings -->

```{r up-down-processing}
preds <- readRDS(here("data", "revised_chng", "predictions_honest.RDS"))
preds <- preds %>% 
  filter(abs(quantile - 0.5) < 1e-6) %>% 
  select(-quantile) %>%
  mutate(forecaster = recode(forecaster,
                             AR3 = "AR",
                             AR3CHCLI3 = "CHNG-CLI",
                             AR3CHCOV3 = "CHNG-COVID",
                             AR3DVCLI3 = "DV-CLI",
                             AR3FBCLI3 = "CTIS-CLIIC",
                             AR3GSSAA3_Subset = "gs_subset",
                             AR3GSSAA3_Zero = "Google-AA",
                             Baseline = "strawman"
  )) %>%
  filter(! forecaster %in% c("gs_subset", "strawman"))

up_down <- actuals %>%
  arrange(geo_value, target_end_date) %>%
  group_by(geo_value) %>%
  left_join(cases7dav, c("target_end_date" = "time_value", "geo_value")) %>%
  mutate(pct_change = (actual - lag(actual,7)) / lag(actual,7),
         udf = case_when(
           pct_change >= .25 ~ "up",
           pct_change <= -.2 ~ "down",
           TRUE ~ "flat")) %>%
  filter(case_num > 30, !is.na(pct_change)) #%>%
  #rename(forecast_date = target_end_date)

corr_df <- left_join(fcasts_honest, preds, 
                     by = c("geo_value", "ahead", "forecaster", 
                            "forecast_date")) %>%
  select(-actual_fd, -starts_with("strawman"), -ae) %>%
  rename(med = value)
rm(preds)

up_down_df <- left_join(corr_df %>% 
                  ungroup() %>%
                  filter(forecaster != "AR"),
                corr_df %>% 
                  ungroup() %>%
                  filter(forecaster == "AR") %>%
                  select(-forecaster, -actual_td) %>%
                  rename(AR_wis = wis, AR_med = med)) %>%
  inner_join(up_down, by = c("geo_value","target_end_date"))
```

```{r upswing-summary, fig.cap="Average difference between the WIS of the AR model and the WIS of the other forecasters. The indicator-assisted forecasters do best during down and flat periods."}
up_down_df_summary <- up_down_df %>%
  group_by(forecaster, udf) %>%
  summarise(mean = Mean(AR_wis - wis))
up_down_df_summary %>%
  ggplot(aes(udf, mean , fill = forecaster)) +
  geom_bar(width = 0.6, position = position_dodge(width=0.6),
           stat = "identity") +
  scale_fill_manual(values = fcast_colors[1:5], guide = guide_legend(nrow = 1)) +
  scale_y_continuous() +
  theme_bw() +
  geom_hline(yintercept = 0) +
  ylab("Mean of WIS(AR) - WIS(F)") +
  xlab("") +
  theme(legend.position = "bottom", legend.title = element_blank())
```  

```{r upswing-summary-remake, fig.cap="REMAKE: Percent change in average WIS of the forecaster (AR or indicator assisted) relative to the baseline. All models perform poorly durning down periods, but the indicators help. During flat periods, the indicators improve slightly over the AR. During up periods, all forecasters do much better than the baseline, but only some do as well as AR."}
up_down_df_summary <- inner_join(
  left_join(
    corr_df, 
    fcasts_honest %>% select(ahead, geo_value, forecast_date, strawman_wis)),
  up_down, by = c("geo_value","target_end_date")) %>%
  group_by(forecaster, udf) %>%
  summarise(mean = Mean(wis) / Mean(strawman_wis) - 1)
up_down_df_summary %>%
  ggplot(aes(udf, mean, fill = forecaster)) +
  geom_bar(width = 0.6, position = position_dodge(width=0.6),
           stat = "identity") +
  scale_fill_manual(values = fcast_colors, guide = guide_legend(nrow = 1)) +
  theme_bw() +
  scale_y_continuous(labels = scales::percent_format()) +
  geom_hline(yintercept = 0) +
  ylab("% change in Forecaster WIS\n relative to Baseline") +
  xlab("") +
  theme(legend.position = "bottom", legend.title = element_blank())
```  

  

```{r upswing-histogram, include=FALSE, fig.width=9, fig.height=4.5}
# Fgure 4
up_down_df %>% 
  group_by(forecaster, udf) %>%
  ggplot(aes(AR_wis - wis, fill = forecaster)) +
  geom_histogram(bins = 100) +
  facet_grid(udf ~ forecaster) +
  theme_bw() +
  ylab("Count") +
  theme(legend.position = "none") +
  scale_fill_manual(values = fcast_colors) +
  scale_y_log10(breaks = c(1,100,10000), 
                labels = trans_format("log10", math_format(10^.x))) +
  coord_cartesian(ylim=c(1,2e4)) +
  xlab("AR WIS - forecaster WIS") +
  geom_vline(xintercept = 0)
```

```{r upswing-histogram-logged, eval = FALSE, fig.cap="Not sure if we want this here. Similar to Figure 5 in the manuscript but taking logs. "}
up_down_df %>% 
  group_by(forecaster, udf) %>%
  ggplot(aes((AR_wis + 1) / (wis + 1), fill = forecaster)) +
  geom_histogram(bins = 100) +
  facet_grid(udf ~ forecaster) +
  theme_bw() +
  ylab("Count") +
  theme(legend.position = "none") +
  scale_fill_manual(values = fcast_colors) +
  scale_x_log10() +
  scale_y_log10(breaks = c(10,1000,100000), 
                labels = trans_format("log10", math_format(10^.x))) +
  xlab("AR WIS - forecaster WIS") +
  geom_vline(xintercept = 1)
```

\clearpage


```{r hotspots-upswing-downswing, fig.cap="Classification and loglikelihood separated into periods of upswing, downswing, and flat cases. Like the analysis of the forecasting task in the main paper (see Figure 7), performance is better during down and flat periods."}
hot_udf <- inner_join(
  hotspots_honest,
  up_down %>% select(geo_value, target_end_date, udf))

cutoff <- mean(hot_udf %>% filter(forecaster == "AR") %>% pull(actual))

con_tab <- hot_udf %>% 
  filter(!is.na(actual)) %>%
  mutate(pred = value > cutoff) %>%
  group_by(forecaster, udf) %>%
  summarise(m = mean(pred != actual)) %>%
  ungroup()

con_tab <- left_join(
  con_tab %>% filter(forecaster != "AR"),
  con_tab %>% filter(forecaster == "AR") %>%
    select(-forecaster) %>%
    rename(mar = m))

llike_tab <- hot_udf %>%
  filter(!is.na(actual)) %>%
  mutate( # kill prob 0-1 predictions
    value = case_when(
      value < 1e-8 ~ 1e-8,
      value > 1-1e-8 ~ 1-1e-8,
      TRUE ~ value
    ),
    llike = (actual == 1) * log(value) + (actual == 0) * log(1 - value)) %>%
  group_by(forecaster, udf) %>%
  summarise(m = mean(llike)) %>%
  ungroup()

llike_tab <- left_join(
  llike_tab %>% filter(forecaster != "AR"),
  llike_tab %>% filter(forecaster == "AR") %>%
    select(-forecaster) %>%
    rename(mar = m))

bind_rows(con_tab %>% mutate(err = "Classification error"), 
          llike_tab %>% mutate(err = "Log likelihood")) %>%
  ggplot(aes(udf, (m - mar) / abs(mar) , fill = forecaster)) +
  geom_bar(width = 0.6, position = position_dodge(width=0.6),
           stat = "identity") +
  scale_fill_manual(values = fcast_colors[1:5], guide = guide_legend(nrow = 1)) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  theme_bw() +
  geom_hline(yintercept = 0) +
  facet_wrap(~err) +
  ylab("Change relative to AR") +
  xlab("") +
  theme(legend.position = "bottom", legend.title = element_blank())
```

```{r hotspots-upswing-downswing-remake, fig.cap="REMAKE: Classification and loglikelihood separated into periods of upswing, downswing, and flat cases. The indicator assisted models always have lower classification error relative to the null classifier, while the AR actually does worse in down and flat periods. In terms of loglikelihood, all forecasters have lower likelihood than the null classifier during up periods. In down and flat periods, the indicators generally improve over the AR, while the are worse during up periods."}
# mycummean <- function(x) {
#   isgood <- ! is.na(x)
#   denom <- cumsum(isgood)
#   x[!isgood] <- 0
#   num <- cumsum(x)
#   y <- num / denom
#   y[is.na(y)] <- .5 # deal with empties at the beginning
#   y
# }
# 
# null_classifier <- readRDS(here("data", 
#                                 "all_signals_wide_as_of_2020-05-18.RDS")) %>%
#   rename(jhu = `value+0:jhu-csse_confirmed_7dav_incidence_prop`) %>%
#   select(geo_value, time_value, jhu) %>%
#   group_by(geo_value) %>%
#   arrange(time_value) %>%
#   mutate(lag_value = lag(jhu, 7),
#          apc = (jhu - lag_value) / lag_value,
#          hot = case_when(
#            apc > .25 & lag_value > 30 ~ 1,
#            apc <= .25 & lag_value > 30 ~ 0),
#          null_class = mycummean(hot))
  
hot_udf <- inner_join(
  hotspots_honest,
  up_down %>% select(geo_value, target_end_date, udf))

cutoff <- mean(hot_udf %>% filter(forecaster == "AR") %>% pull(actual))

con_tab <- hot_udf %>% 
  filter(!is.na(actual)) %>%
  mutate(pred = value > cutoff) %>%
  group_by(forecaster, udf) %>%
  summarise(m = (mean(pred != actual) - cutoff) / cutoff,
            err = mean(pred != actual)) %>%
  ungroup()

# con_tab <- left_join(
#   con_tab %>% filter(forecaster != "AR"),
#   con_tab %>% filter(forecaster == "AR") %>%
#     select(-forecaster) %>%
#     rename(mar = m))

llike_tab <- hot_udf %>%
  filter(!is.na(actual)) %>%
  # left_join(null_classifier %>% select(geo_value, time_value, null_class) %>%
  #             rename(target_end_date = time_value)) %>%
  mutate( # kill prob 0-1 predictions
    value = case_when(
      value < 1e-8 ~ 1e-8,
      value > 1-1e-8 ~ 1-1e-8,
      TRUE ~ value),
    # null_class = case_when(
    #   null_class < 1e-8 ~ 1e-8,
    #   null_class > 1-1e-8 ~ 1-1e-8,
    #   TRUE ~ null_class),
    llike = (actual == 1) * log(value) + (actual == 0) * log(1 - value),
    nulldev = (actual == 1) * log(cutoff) + 
      (actual == 0) * log(1 - cutoff)) %>%
  group_by(forecaster, udf) %>%
  summarise(m = (mean(llike) - mean(nulldev)) / abs(mean(nulldev)),
            mm = mean(llike),
            mmm = mean(nulldev)) %>%
  ungroup()

# llike_tab <- left_join(
#   llike_tab %>% filter(forecaster != "AR"),
#   llike_tab %>% filter(forecaster == "AR") %>%
#     select(-forecaster) %>%
#     rename(mar = m))

bind_rows(con_tab %>% mutate(err = "Classification error"), 
          llike_tab %>% mutate(err = "Log likelihood")) %>%
  ggplot(aes(udf, m , fill = forecaster)) +
  geom_bar(width = 0.6, position = position_dodge(width=0.6),
           stat = "identity") +
  scale_fill_manual(values = fcast_colors, guide = guide_legend(nrow = 1)) +
  #scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  theme_bw() +
  geom_hline(yintercept = 0) +
  scale_y_continuous(labels = scales::percent_format()) +
  facet_wrap(~err, scales = "free_y") +
  ylab("Improvement relative to the null classifier") +
  xlab("") +
  theme(legend.position = "bottom", legend.title = element_blank())
```

\clearpage



<!-- Correlations with lagged actuals -->

```{r cor-with-actuals}
comparison_df <- left_join(
  fcasts_honest %>% filter(forecaster != "AR"),
  fcasts_honest %>% filter(forecaster == "AR") %>%
    select(-c(forecaster,target_end_date)) %>%
    rename(ar3_wis = wis),
  by = c("geo_value", "ahead", "forecast_date")) %>%
  group_by(forecaster, forecast_date, geo_value) %>%
  summarize(wis_ratio = mean(wis) / mean(ar3_wis), .groups = "drop") 

pct_chng_df <- readRDS(here(
  "data", 
  "confirmed_7dav_incidence_num.RDS")) %>%
  pct_change(n = 7) %>%
  select(geo_value, time_value, pct_change) %>%
  filter(time_value %in% unique(comparison_df$forecast_date))

comparison_df <- comparison_df %>% 
  left_join(pct_chng_df, 
            by = c("forecast_date" = "time_value", "geo_value"))

pct_chng_df <- comparison_df %>% 
  group_by(forecaster, geo_value) %>%
  summarize(
    cor_wisratio_pctchange = cor(wis_ratio, pct_change, method = "spearman"),
    cor_abs_wisratio_minus_1_pctchange = cor(
      abs(wis_ratio - 1), pct_change,method = "spearman"), .groups = "drop")
```

```{r cor-wis-ratio, fig.cap="Histograms of the Spearman correlation between the ratio of AR to AR WIS with the percent change in smoothed case rates relative to 7 days earlier."}
ggplot(pct_chng_df %>% 
         group_by(forecaster) %>% 
         mutate(median = median(cor_wisratio_pctchange)), 
       aes(x = cor_wisratio_pctchange)) +
  geom_histogram(aes(y = ..count.. / sum(..count..), fill = forecaster), bins = 50) +
  scale_fill_manual(values = fcast_colors) +
  theme_bw() +
  theme(legend.position = "none") +
  geom_vline(aes(xintercept = median), linetype = "dotted") + 
  geom_vline(xintercept = 0) +
  facet_wrap(~forecaster) + 
  xlab("Spearman correlation") + ylab("Relative frequency") +
  scale_y_continuous(labels = scales::label_percent(accuracy = .1))
```

\clearpage

```{r cor-wis-ratio-m1, eval = FALSE, fig.cap="This is Alden's second set of histograms. Here we have the correlation of the absolute value of WIS ratio - 1 with the percent change in 7dav cases relative to 7 days earlier"}
ggplot(pct_chng_df %>% 
         group_by(forecaster) %>% 
         mutate(median = median(cor_abs_wisratio_minus_1_pctchange)), 
       aes(x = cor_abs_wisratio_minus_1_pctchange)) +
  geom_histogram(aes(y = ..count.. / sum(..count..), fill = forecaster), bins = 50) +
  scale_fill_manual(values = fcast_colors) +
  theme_bw() +
  theme(legend.position = "none") +
  geom_vline(aes(xintercept = median), linetype = "dotted") + 
  geom_vline(xintercept = 0) +
  facet_wrap(~forecaster) + 
  xlab("Spearman correlation") + ylab("Relative frequency") +
  scale_y_continuous(labels = scales::label_percent(accuracy = 1))
```

\clearpage


```{r upswing-corr-table, fig.cap="Correlation of the difference in WIS with the difference in median predictions for the AR model relative to the indicator-assisted forecaster. In down periods, improvements in forecast risk are highlycorrelated with lower median predictions. The opposite is true in up periods. This suggests, as one might expect that improved performance of the indicator-assisted model is attributable to being closer to the truth then the AR model. This conclusion is stronger in down periods then in up periods."}
up_down_df %>% 
  group_by(forecaster, udf) %>%
  summarise(cor = cor(AR_wis - wis, AR_med - med)) %>%
  ggplot(aes(udf, cor , fill = forecaster)) +
  geom_bar(width = 0.6, position = position_dodge(width=0.6),
           stat = "identity") +
  scale_fill_manual(values = fcast_colors[1:5], guide = guide_legend(nrow = 1)) +
  theme_bw() +
  geom_hline(yintercept = 0) +
  theme(legend.position = "bottom", legend.title = element_blank())

# up_down_df %>% 
#   filter(period != "jm") %>% 
#   group_by(forecaster, udf) %>%
#   summarise(cor = cor(AR_wis - wis, AR_med - med)) %>%
#   pivot_wider(names_from = forecaster, values_from = cor) %>%
#   kableExtra::kbl(
#     booktabs = TRUE, digits = 2, centering = TRUE,
#     caption = paste("Correlation of the difference in WIS between the AR",
#                    "model with the difference in median predictions. In down",
 #                   "periods, improvements in forecast risk are highly",
#                    "correlated with lower median predictions. The opposite",
#                    "is true in up periods. This suggests, as one might expect",
#                    "that improved performance of the indicator-assisted",
#                    "model is attributable to being closer to the truth then",
#                    "the AR model. This conclusion is stronger in down",
#                    "periods then in up periods."))
```

\clearpage



<!-- Leadingness and laggingness -->

```{r lead-lag-processing}
# see lead-lag-analysis.R for signal downloading and processing
lead_lag <- function(x, y, lag.max = NULL, na.len = 14) {
  if (sum(is.na(x)) >= na.len || sum(is.na(y)) >= na.len) {
    return(c(leading = NA, lagging = NA))
  }
  out <- ccf(x, y, lag.max = lag.max, plot = FALSE, na.action = na.omit)
  clim <- qnorm((1 + .9) / 2) / sqrt(out$n.used)
  lag_vec <- drop(out$lag)
  cc <- drop(out$acf)
  cc <- cc * (cc > clim)
  return(c(leading = mean(cc[lag_vec < 0]),
           lagging = mean(cc[lag_vec > 0])))
}

slide_lead_lag <- function(x, y, min_len = 56, lag.max = NULL, na.len = 14) {
  n <- length(x)
  outlist <- list()
  idx <- 1:min_len
  for (i in min_len:n) {
    outlist[[i]] <- lead_lag(x[idx], y[idx], lag.max, na.len)
    idx <- idx + 1
  }
  outlist <- bind_rows(outlist)
  bind_rows(
    tibble(leading = rep(NA, min_len-1), lagging = rep(NA, min_len -1)),
    outlist)
}

all_sigs <- readRDS(here("data", "all_signals_wide_as_of_2020-05-18.RDS"))

all_sigs_imputed <- all_sigs %>% 
  group_by(geo_value) %>% 
  arrange(time_value) %>%
  mutate(across(contains("value+0"), 
                ~zoo::na.locf(.x, na.rm = FALSE, maxgap = 13))) %>%
  pivot_longer(contains("value+0"))

sigs_cor <- left_join(
  all_sigs_imputed %>% filter(! str_detect(name, "jhu-csse")),
  all_sigs_imputed %>% filter(str_detect(name, "jhu-csse")) %>%
    select(-name) %>%
    rename(cases = value))

lead_lag_metric <- sigs_cor %>% 
  group_by(geo_value, name) %>%
  arrange(time_value) %>%
  group_modify(~ {
    bind_cols(time_value = .x$time_value, slide_lead_lag(.x$value, .x$cases))
  })

lead_lag_metric <- lead_lag_metric %>%
  mutate(
    forecaster = recode(
      name,
      `value+0:chng_smoothed_adj_outpatient_cli` = "CHNG-CLI",
      `value+0:chng_smoothed_adj_outpatient_covid` = "CHNG-COVID",
      `value+0:doctor-visits_smoothed_adj_cli` = "DV-CLI",
      `value+0:fb-survey_smoothed_hh_cmnty_cli` = "CTIS-CLIIC",
      `value+0:google-symptoms_sum_anosmia_ageusia_smoothed_search` = "Google-AA")) %>%
  ungroup() %>%
  select(-name)

df2 <- left_join(
  up_down_df, 
  lead_lag_metric,
  by = c("geo_value","forecaster","target_end_date" = "time_value"))
```


```{r leading-only, include=FALSE, fig.width=6, fig.height=4}
# Figure 5 in the manuscript
df2 %>%
  group_by(forecaster, udf) %>%
  summarise(
    leadingness = cor(AR_wis - wis, leading, use = "pairwise.complete.obs"),
    laggingness = cor(AR_wis - wis, lagging, use = "pairwise.complete.obs")) %>%
  ggplot(aes(udf, leadingness, fill = forecaster)) +
  geom_bar(width = 0.6, position = position_dodge(width=0.6),
           stat = "identity") +
  geom_hline(yintercept = 0) +
  scale_fill_manual(values = fcast_colors[1:5]) +
  guides(fill = guide_legend(nrow = 1)) +
  theme_bw() +
  ylab("Correlation") +
  xlab("") +
  theme(legend.position = c(1,-.15), 
        legend.justification = "right",
        legend.title = element_blank(), 
        legend.text = element_text(size = 10),
        plot.margin = margin(b = 20, l = 4),
        legend.background = element_rect(fill = "transparent"))
```



```{r leading-and-lagging, eval=FALSE}
# Deprecated
df2 %>%
  group_by(forecaster, udf) %>%
  summarise(
    leadingness = cor(AR_wis - wis, leading, use = "pairwise.complete.obs"),
    laggingness = cor(AR_wis - wis, lagging, use = "pairwise.complete.obs")) %>%
  pivot_longer(leadingness:laggingness) %>%
  ggplot(aes(udf, value, fill = forecaster)) +
  geom_bar(width = 0.6, position = position_dodge(width=0.6),
           stat = "identity") +
  geom_hline(yintercept = 0) +
  scale_fill_manual(values = fcast_colors) +
  facet_wrap(~name) +
  theme_bw() +
  ylab("Correlation") +
  xlab("") +
  theme(legend.position = "bottom", legend.title = element_blank())
```

```{r ccf-dv-finalized, eval=TRUE, fig.cap="Illustration of the cross-correlation function between DV-CLI and cases. The left panel shows the standardized signals over the period from August 1 to September 28 (as of May 15, 2021). The right panel shows $\\CCF_{\\ell}(a)$ for different values of $a$ as vertical blue bars. The orange dashed lines indicate the 95\\% significance threshold. By our leadingness/laggingness metric, DV-CLI is leading (but notlagging) cases over this period."}
source(here("code", "figures", "ccf-dv-finalized.R"))
gg
```

\clearpage


```{r lagging-only, fig.cap="Correlation of the difference in WIS with the  laggingness of the indicator at the target date, stratified by up, down, or flat period. Compare to Figure 5 in the manuscript."}
# Deprecated
df2 %>%
  group_by(forecaster, udf) %>%
  summarise(
    leadingness = cor(AR_wis - wis, leading, use = "pairwise.complete.obs"),
    laggingness = cor(AR_wis - wis, lagging, use = "pairwise.complete.obs")) %>%
  ggplot(aes(udf, laggingness, fill = forecaster)) +
  geom_bar(width = 0.6, position = position_dodge(width=0.6),
           stat = "identity") +
  geom_hline(yintercept = 0) +
  scale_fill_manual(values = fcast_colors[1:5], guide = guide_legend(nrow = 1)) +
  theme_bw() +
  ylab("Correlation") +
  xlab("") +
  theme(legend.position = "bottom", legend.title = element_blank())
```

\clearpage

```{r diff-in-lead-lag, fig.cap = "Correlation of the difference between leadingness and laggingness with the difference in WIS. The relationship is essentially the same as described in the manuscript and shown in Figure 5."}
# Deprecated
df2 %>%
  group_by(forecaster, udf) %>%
  summarise(cor = cor(AR_wis - wis, leading - lagging, 
                      use = "pairwise.complete.obs")) %>%
  ggplot(aes(udf, cor, fill = forecaster)) +
  geom_bar(width = 0.6, position = position_dodge(width=0.6),
           stat = "identity") +
  geom_hline(yintercept = 0) +
  scale_fill_manual(values = fcast_colors[1:5]) +
  theme_bw() +
  ylab("Correlation") +
  xlab("") +
  theme(legend.position = "bottom", legend.title = element_blank())
```



\clearpage





<!-- Figures in the manuscript in their own scripts -->


```{r revisions-dv-jhu, eval=FALSE}
# Figure 1 in the manuscript
source(here("code", "figures", "revisions.R"))
```





```{r ny-trajectory, eval=FALSE}
# Figure 2 in the manuscript
source(here("code", "figures", "trajectory.R"))
gg
```









\clearpage


<!-- Cumulative Mean -->

```{r cumulative-mean, fig.cap="This figure shows the cumulative sum of WIS for each forecaster divided by the cumulative sum of WIS for the baseline model. The shaded background shows total U.S. cases as reported by JHU-CSSE for the 14-day ahead target. Hashes along the $x$-axis denote weeks." }
cumulatives <- fcasts_honest %>%
  group_by(forecaster, forecast_date) %>%
  summarise(mw = Mean(wis),
            smw = Mean(strawman_wis),
            gmw = GeoMean(wis / strawman_wis)) %>%
  arrange(forecast_date) %>%
  mutate(`Cumulative Mean` = cummean(mw) / cummean(smw),
         `Cumulative Sum` = cumsum(mw) / cumsum(smw),
         `Cumulative Geo Mean` = exp(cummean(log(gmw))),
         `GM Regret` = cumsum(gmw) - cumsum(smw/smw),
         `AM Regret` = cumsum(mw) - cumsum(smw),
         `14 day trailing average` = RcppRoll::roll_meanl(mw / smw, n = 14L))

us_cases <- covidcast::covidcast_signal(
  "jhu-csse", "confirmed_7dav_incidence_num", "2020-03-01", "2021-02-01",
  geo_type = "nation") %>% as_tibble() %>%
  mutate(value = (value / max(value)) * .25 +  .75) %>%
  filter(time_value > "2020-06-01")
ticks <- seq(min(us_cases$time_value), max(us_cases$time_value), by = 7) - 14


ggplot(cumulatives %>% filter(forecast_date < "2021-01-01")) + 
  geom_line(aes(forecast_date, y = `Cumulative Sum`, color = forecaster)) +
  annotate(x = us_cases$time_value - 14, ymax = us_cases$value, ymin = -Inf,
           geom = "ribbon", alpha = .1) +
  annotate("segment", x=ticks, y=-Inf, xend = ticks, yend = .77, 
               color = "grey70") +
  geom_hline(yintercept = 1) +
  xlab("forecast date") +
  coord_cartesian(#ylim = c(.76, 1), 
                  xlim = ymd(c("2020-06-01", "2021-01-01"))) +
  scale_x_date(date_breaks = "2 months", date_minor_breaks = "1 week",
               date_labels = "%b %Y") +
  scale_color_manual(values = fcast_colors, guide = guide_legend(nrow = 1)) +
  theme_bw() +
  theme(legend.position = "bottom", legend.title = element_blank(),
        panel.grid.minor.x = element_blank())
```

\clearpage

```{r cumulative-geo-mean, fig.cap="This figure shows the cumulative geometric mean of WIS for each forecaster divided by the WIS for the baseline model. The shaded background shows total U.S. cases as reported by JHU-CSSE for the 14-day ahead target. Hashes along the $x$-axis denote weeks." }
ggplot(cumulatives %>% filter(forecast_date < "2021-01-01")) + 
  geom_line(aes(forecast_date, y = `Cumulative Geo Mean`, color = forecaster)) +
  annotate(x = us_cases$time_value - 14, ymax = us_cases$value, ymin = -Inf,
           geom = "ribbon", alpha = .1) +
  annotate("segment", x=ticks, y=-Inf, xend = ticks, yend = .77, 
               color = "grey70") +
  geom_hline(yintercept = 1) +
  xlab("forecast date") + ylab("Cumulative Geometric Mean") +
  coord_cartesian(#ylim = c(.76, 1), 
                  xlim = ymd(c("2020-06-01", "2021-01-01"))) +
  scale_x_date(date_breaks = "2 months", date_minor_breaks = "1 week",
               date_labels = "%b %Y") +
  scale_color_manual(values = fcast_colors, guide = guide_legend(nrow = 1)) +
  theme_bw() +
  theme(legend.position = "bottom", legend.title = element_blank(),
        panel.grid.minor.x = element_blank())
```

\clearpage

```{r errs-in-space, fig.cap="Percent improvement in WIS relative to the AR forecaster by region (negative numbers indicate improved performance, positives indicate worsening)."}
# fig.height = 9.6, fig.width = 6, out.width = "5in", out.height="8in", 
by_hrr <- fcasts_honest %>% 
  group_by(forecaster, geo_value) %>% 
  summarize(value = GeoMean(wis)) %>%
  mutate(time_value = Sys.Date()) %>%
  ungroup()
by_hrr <- left_join(
  by_hrr %>% filter(forecaster != "AR"), 
  by_hrr %>% 
    filter(forecaster == "AR") %>% 
    rename(AR = value) %>%
    select(geo_value, AR)) %>%
  mutate(value = (value - AR) / AR * 100) %>%
  group_by(forecaster) %>%
  group_split()

cc_sigs <- purrr::map(by_hrr,
                   ~ as.covidcast_signal(
                     .x, signal = "Improvement relative to AR",
                     data_source = .x$forecaster[1],
                     geo_type = "hrr"))
br <- c(2.5, 5, 10, 25, 50)
br <- c(-rev(br), 0, br)
colours <- brewer_pal(palette = "RdBu")


maps <- purrr::map(
  cc_sigs, 
  ~plot(.x, title = .x$forecaster[1], 
        choro_params = list(breaks = br), 
        choro_col = rev(colours(11))) +
    theme(legend.position = "none"))

map_plot <- cowplot::plot_grid(plotlist = maps, ncol = 3)
map_leg <- get_legend(maps[[1]] + theme(legend.position = "bottom"))
cowplot::plot_grid(map_plot, map_leg, ncol = 1, rel_heights = c(1, .1))
```

\clearpage

<!-- Comparison to submitted forecasts -->

```{r grab-submitted-case-fcasts}
library(aws.s3)
Sys.setenv("AWS_DEFAULT_REGION" = "us-east-2")
s3bucket <- get_bucket("forecast-eval")
# ensure that forecasters have submitted a reasonable amount
n_keeper_weeks <- 6L
n_keeper_locs <- 50L
case_scores <- s3readRDS("score_cards_state_cases.rds", s3bucket) %>% 
  mutate(forecast_date = target_end_date - ahead * 7) %>% 
  # fix weirdnesses about submission dates, 
  # this is generous to the forecaster
  filter(forecast_date < "2021-01-01", ahead < 4) %>% 
  select(ahead, geo_value, forecaster, target_end_date, wis, forecast_date)

strawman <- case_scores %>% filter(forecaster == "COVIDhub-baseline")
case_scores <- left_join(
  case_scores, 
  strawman %>% 
    select(forecast_date, target_end_date, geo_value, wis) %>% 
    rename(strawman_wis = wis)
) %>% filter(forecaster != "COVIDhub-baseline")

# Subset to those forecasters that submitted enough 14-day ahead forecasts
n_submitted <- case_scores %>% 
  filter(ahead == 2) %>% 
  group_by(forecaster) %>% 
  summarise(nfcasts = n())
keepers <- n_submitted %>% 
  filter(nfcasts / n_keeper_locs > n_keeper_weeks - .0001, 
         forecaster != "COVIDhub-4_week_ensemble") %>% # same as CH-Ensemble 
  pull(forecaster)

case_scores <- case_scores %>% 
  filter(forecaster %in% keepers) %>%
  group_by(forecaster, ahead) %>%
  summarise(rel_wis = Mean(wis) / Mean(strawman_wis),
            geo_wis1 = GeoMean((wis + 1) / (strawman_wis + 1)),
            geo_wis = GeoMean(wis / strawman_wis))
```

```{r compare-to-hub-mean, fig.height = 8.5, fig.cap="This figure reproduces Figure 3 in the main paper but overlays scores for the forecasts submitted to the COVID-19 Forecast Hub. Grey lines correspond to the various teams that submitted during period our evaluation period. We have highlighted the COVIDhub-ensemble, which is the official forecast of the CDC.", include=FALSE}
# Same as Fig 3 in the paper
df <- summarizer(fcasts_honest %>%
                   group_by(ahead, forecaster), "wis", NULL, 
                 "strawman_wis", Mean, c("aggr","scale"))
ggplot(df) +
  geom_line(aes(ahead, wis, color = forecaster)) + 
  geom_point(aes(ahead, wis, color = forecaster)) +
  theme_bw() +
  geom_hline(yintercept = 1, size = 1.5) +
  xlab("Days ahead") +
  ylab("Mean WIS (relative to baseline)") +
  scale_color_manual(values = c(fcast_colors, "CH-ensemble" = "lightblue"),
                     guide = guide_legend(nrow = 2)) +
  theme(legend.position = "bottom", legend.title = element_blank()) +
  geom_line(data = case_scores, 
            aes(ahead * 7, rel_wis, group = forecaster),
            color = "grey70") +
  geom_line(data = case_scores %>% filter(forecaster == "COVIDhub-ensemble"),
            aes(ahead * 7, rel_wis), color = "lightblue", size = 1.5) +
  scale_y_log10()
```

\clearpage

```{r compare-to-hub-geomean, fig.height = 8.5, fig.cap="This figure is similar to Figure \\ref{fig:fcast-adjusted}. In this case, we add 1 to both the forecaster WIS and the baseline WIS before scaling (to allow forecasters that achieve 0 error to appear), and we overlay scores for the forecasts submitted to the COVID-19 Forecast Hub. Grey lines correspond to the various teams that submitted during period our evaluation period. We have highlighted the COVIDhub-ensemble, which is the official forecast of the CDC.", include=FALSE}
# Like supplement GeoMean figure, but adding 1
df2 <- fcasts_honest %>% 
  group_by(ahead, forecaster) %>%
  summarise(wis = GeoMean((wis + 1) / (strawman_wis + 1)))

ggplot(df2) +
  geom_line(aes(ahead, wis, color = forecaster)) + 
  geom_point(aes(ahead, wis, color = forecaster)) +
  theme_bw() +
  geom_hline(yintercept = 1, size = 1.5) +
  xlab("Days ahead") +
  ylab("Geometric mean of WIS (relative to baseline)") +
  scale_color_manual(values = c(fcast_colors, "CH-ensemble" = "lightblue"),
                     guide = guide_legend(nrow = 2)) +
  theme(legend.position = "bottom", legend.title = element_blank()) +
  geom_line(data = case_scores, 
            aes(ahead * 7, geo_wis1, group = forecaster),
            color = "grey70") +
  geom_line(data = case_scores %>% filter(forecaster == "COVIDhub-ensemble"),
            aes(ahead * 7, geo_wis1), color = "lightblue", size = 1.5) +
  scale_y_log10()
```


<!-- All code below is deprecated -->


```{r fcast-gs-locations, eval=FALSE}
plotter(fcasts_gs %>% filter(period != "jm"),
        "wis", Mean, scaler = "strawman_wis", 
        order_of_operations = c("aggr","scale")) +
  ylab("Mean WIS (relative to baseline)")
```

```{r fcast-gs-locations-adjusted, eval=FALSE}
plotter(fcasts_gs %>% filter(period != "jm"), 
        "wis", GeoMean, scaler = "strawman_wis", 
        order_of_operations = c("scale","aggr")) +
  ylab("Geometric mean of WIS (relative to baseline)")
```

```{r hot-gs-locations, eval=FALSE}
plotter_hotspots(hotspots_gs %>% filter(period != "jm")) +
  geom_hline(yintercept = 0.5)
```



```{r traj-data, eval = FALSE}
source(here("code", "deprecated", "trajectory_plot_funs.R"))
preds <- readRDS(here("data", "predictions_honest.RDS"))
traj_best <- get_trajectory_plots(fcasts_honest, preds, actuals, hrr_tab, 
                                  "only2020", "best")
traj_worst <- get_trajectory_plots(fcasts_honest, preds, actuals, hrr_tab,
                                   "only2020", "worst")
rm(preds)
```

```{r trajectory-plots, eval = FALSE}
for (nm in names(traj_best)) print(trajectory_panel(nm, traj_best, traj_worst))
```

